version: '3.8'

services:
  # PostgreSQL Database for Local Development
  db:
    image: postgres:15-alpine
    container_name: gsc_db_local
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-gsc_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - gsc_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-gsc_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Local Development (Optional)
  redis:
    image: redis:7-alpine
    container_name: gsc_redis_local
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data_local:/data
    networks:
      - gsc_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data_local:
    driver: local
  redis_data_local:
    driver: local

networks:
  gsc_network:
    driver: bridge