// Export all home page components
export { Hero } from './Hero';
export { WhyChooseUs } from './WhyChooseUs';
export { HowWeWork } from './HowWeWork';
export { ServicesGrid } from './ServicesGrid';
export { CRMShowcase } from './CRMShowcase';
export { PortfolioPreview } from './PortfolioPreview';
export { SocialProof } from './SocialProof';
export { CTAStrip } from './CTAStrip';